services:
  - type: web
    name: habit-tracker-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd habit-backend && npm install
    startCommand: cd habit-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
