[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://habit-u7uw.onrender.com"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
